name: t29ndrbx
description: Applifys mobile application.
publish_to: 'none'

# 애플 GPS 사용 기능 삭제 및 푸시 알림 기능 개선 업데이트(2024-11-26) 2.2.1+25
# travelbox 외부 브라우저 열기 업데이트 및 UI 수정(2024-11-27) 2.2.2+26
version: 2.2.3+27

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  win32: ^5.7.1
  splash_view: ^2.0.1
  flutter_launcher_icons: ^0.11.0
  url_launcher: ^6.0.9
  awesome_dialog: 2.2.1
  flutter_inappwebview: ^6.1.5
  flutter_spinkit: ^5.1.0
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^17.2.4
  android_intent_plus: ^5.2.0
  intl: ^0.18.0
  permission_handler: ^10.2.0
  cloud_firestore: ^4.5.0
  http: ^0.13.6
  firebase_auth: ^4.10.1
  geolocator: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon.png"
  image_path_android: "assets/images/icon.png"
  image_path_ios: "assets/images/icon.png"
  android: true
  ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: my_font
      fonts:
        - asset: assets/fonts/font.ttf
