# Generated by Django 4.2.7 on 2024-10-25 06:30

import _jejuya.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACCESS_IP',
            fields=[
                ('ip', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('count', models.DecimalField(decimal_places=0, help_text='accessible count', max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='ACCOUNT',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=300)),
                ('device_token', models.CharField(blank=True, max_length=300, null=True)),
                ('account_type', models.CharField(max_length=30)),
                ('dt', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='AROUND',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20)),
                ('around_type', models.CharField(max_length=30)),
                ('categories', models.CharField(max_length=300)),
                ('open_time', models.CharField(max_length=100)),
                ('holiday', models.CharField(max_length=100)),
                ('reserve_link', models.CharField(max_length=300)),
                ('note', models.TextField()),
                ('medias', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='POINT',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('rooms_cnt', models.IntegerField()),
                ('tel', models.CharField(max_length=20)),
                ('note', models.TextField()),
                ('medias', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SCHEDULE',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=64)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SCHEDULE_ITEM',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('schedule_id', models.CharField(max_length=16)),
                ('around_id', models.CharField(max_length=16)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UPLOAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=_jejuya.models.upload_to)),
            ],
        ),
    ]
